services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 1s
      timeout: 2s
      retries: 10
      start_period: 2s
  backend:
    build: ./backend/
    container_name: backend
    ports:
      - "127.0.0.1:5003:5003"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    healthcheck:
      test: ["CMD-SHELL", "wget --spider http://localhost:5003/health"]
      interval: 1s
      timeout: 2s
      retries: 10
      start_period: 10s
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "127.0.0.1:5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    

volumes:
  postgres_data: